"""Add youtube_url to CollaborationPost

Revision ID: 4fdf5400caaf
Revises: dd2592a4fe85
Create Date: 2026-05-30 14:47:34.582288

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4fdf5400caaf"
down_revision: Union[str, Sequence[str], None] = "dd2592a4fe85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collaboration_posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("youtube_url", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collaboration_posts", schema=None) as batch_op:
        batch_op.drop_column("youtube_url")

    # ### end Alembic commands ###
