"""add_collaboration

Revision ID: 82813ce3f0b9
Revises: fee6efe22207
Create Date: 2026-05-28 23:02:52.053753

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82813ce3f0b9"
down_revision: Union[str, Sequence[str], None] = "fee6efe22207"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collaboration_posts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("post_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("collaboration_posts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_collaboration_posts_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_collaboration_posts_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "practice_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("video_url", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("logged_date", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("practice_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_practice_logs_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_practice_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "collaboration_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["post_id"], ["collaboration_posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("collaboration_comments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_collaboration_comments_post_id"), ["post_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_collaboration_comments_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "post_options",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("option_text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["collaboration_posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("post_options", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_post_options_post_id"), ["post_id"], unique=False)

    op.create_table(
        "post_schedule_times",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("time_slot", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["collaboration_posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("post_schedule_times", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_post_schedule_times_post_id"), ["post_id"], unique=False
        )

    op.create_table(
        "user_availabilities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("schedule_time_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_time_id"], ["post_schedule_times.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_availabilities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_availabilities_schedule_time_id"),
            ["schedule_time_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_availabilities_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_votes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("option_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["option_id"], ["post_options.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_votes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_votes_option_id"), ["option_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_votes_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_votes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_votes_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_votes_option_id"))

    op.drop_table("user_votes")
    with op.batch_alter_table("user_availabilities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_availabilities_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_availabilities_schedule_time_id"))

    op.drop_table("user_availabilities")
    with op.batch_alter_table("post_schedule_times", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_schedule_times_post_id"))

    op.drop_table("post_schedule_times")
    with op.batch_alter_table("post_options", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_options_post_id"))

    op.drop_table("post_options")
    with op.batch_alter_table("collaboration_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collaboration_comments_user_id"))
        batch_op.drop_index(batch_op.f("ix_collaboration_comments_post_id"))

    op.drop_table("collaboration_comments")
    with op.batch_alter_table("practice_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_practice_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_practice_logs_project_id"))

    op.drop_table("practice_logs")
    with op.batch_alter_table("collaboration_posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collaboration_posts_user_id"))
        batch_op.drop_index(batch_op.f("ix_collaboration_posts_project_id"))

    op.drop_table("collaboration_posts")
    # ### end Alembic commands ###
