"""remove score and tab features

Revision ID: 1af709ba7780
Revises: 0e79723710dd
Create Date: 2026-05-29 22:58:02.327307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af709ba7780'
down_revision: Union[str, Sequence[str], None] = '0e79723710dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_assets_project_id'))

    op.drop_table('project_assets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_assets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('asset_type', sa.VARCHAR(), nullable=True),
    sa.Column('instrument', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_assets_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###
