"""add_practice_deadline_and_vlog_fields

Revision ID: 49423a945686
Revises: 06f27e42cbfb
Create Date: 2026-06-03 18:42:04.330040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49423a945686'
down_revision: Union[str, Sequence[str], None] = '06f27e42cbfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaboration_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.String(), nullable=True))
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_collaboration_posts_team_id'), ['team_id'], unique=False)
        batch_op.create_foreign_key('fk_collaboration_posts_team_id', 'teams', ['team_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('practice_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_practice_logs_team_id'), ['team_id'], unique=False)
        batch_op.create_foreign_key('fk_practice_logs_team_id', 'teams', ['team_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument', sa.String(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practice_deadline', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('merged_vlog_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('merged_vlog_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_projects_team_id', 'teams', ['team_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_team_id', type_='foreignkey')
        batch_op.drop_column('team_id')
        batch_op.drop_column('merged_vlog_status')
        batch_op.drop_column('merged_vlog_url')
        batch_op.drop_column('practice_deadline')

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_column('instrument')

    with op.batch_alter_table('practice_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_practice_logs_team_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_practice_logs_team_id'))
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('team_id')

    with op.batch_alter_table('collaboration_posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_collaboration_posts_team_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_collaboration_posts_team_id'))
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###
